#!/bin/bash
echo "🚀 ProjectFlow - Setup Guide"
echo "================================"
echo ""
echo "📦 BACKEND SETUP:"
echo "  cd backend"
echo "  pip install -r requirements.txt"
echo "  python seed.py          # create demo data"
echo "  uvicorn main:app --reload --port 8000"
echo ""
echo "🌐 FRONTEND SETUP (new terminal):"
echo "  cd frontend"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "🔗 URLs:"
echo "  Frontend:  http://localhost:5173"
echo "  API Docs:  http://localhost:8000/docs"
echo ""
echo "🔐 Demo Accounts:"
echo "  admin@test.com  / admin123  (Admin)"
echo "  alice@test.com  / user123   (User)"
echo "  bob@test.com    / user123   (User)"
echo "  carol@test.com  / user123   (User)"
